name: C Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install GCC
        run: sudo apt-get install gcc -y

      # Compile the C program
      - name: Compile Calculator App
        run: gcc app/calculator.c -o EXE_calculator

      - name: Make calculator_test_file.sh executable
        run: chmod +x ./calculator_test_file.sh

      # Run tests
      - name: Run Tests
        run: ./calculator_test_file.sh
