name: Calculator Tests by @Balaji303

# Trigger Pipeline on these conditions
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    #Environment is based on Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install GCC
        run: sudo apt-get install gcc -y

      # Compile the C program
      - name: Compile Calculator App
        run: gcc app/calculator.c -o EXE_calculator

      # Give permission to run shell script
      - name: Make calculator_test_file.sh executable
        run: chmod +x ./calculator_test_file.sh

      # Run shell script tests
      - name: Run Tests
        run: ./calculator_test_file.sh
